default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: changeme
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: star_money_cron_development
test:
  <<: *default
  database: myapp_test
production:
  <<: *default
  database: myapp_production

